apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: piai-analyst-ui-secrets
  namespace: $(PIAI.Analyst.UI.EKS.Namespace)
spec:
  provider:
    aws:
      service: SecretsManager
      region: $(PIAI.AWS.DefaultRegion)
      auth:
        jwt:
          serviceAccountRef:
            name: $(PIAI.AWS.Secrets.ServiceAccount)
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: piai-analyst-ui-secrets
  namespace: $(PIAI.Analyst.UI.EKS.Namespace)
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: piai-analyst-ui-secrets
    kind: SecretStore
  target:
    name: piai-analyst-ui-secrets
    creationPolicy: Owner
  data:
  - secretKey: $(PIAI.AWS.SecretKey.OPENAI_API_KEY)
    remoteRef:
      key: $(PIAI.AWS.SecretName)
      property: $(PIAI.AWS.SecretKey.OPENAI_API_KEY)
  - secretKey: $(PIAI.AWS.SecretKey.VITE_MSAL_CLIENT_ID)
    remoteRef:
      key: $(PIAI.AWS.SecretName)
      property: $(PIAI.AWS.SecretKey.VITE_MSAL_CLIENT_ID)
  - secretKey: $(PIAI.AWS.SecretKey.VITE_MSAL_TENANT_ID)
    remoteRef:
      key: $(PIAI.AWS.SecretName)
      property: $(PIAI.AWS.SecretKey.VITE_MSAL_TENANT_ID)