/*
Live SQL Server schema from INFORMATION_SCHEMA and key metadata.
Reviewed relationships:
- edi_pharm_universal.claimid = claim.claimid
- edi_pharm_universal.claimid = claimpharm.claimid
- edi_pharm_universal.claimline = claimpharm.claimline
*/
CREATE TABLE [plandata_rx_production].[dbo].[edi_pharm_universal]
(
    [processid] char(15) NOT NULL, -- PK marker: X | FK marker: X
    [claimid] char(15) NOT NULL, -- PK marker: X | FK marker: X
    [claimline] int NOT NULL, -- PK marker: X
    [rxnumber] char(15) NOT NULL,
    [rxdate] char(10) NOT NULL,
    [metricqty] money NOT NULL,
    [ndcmfgcode] char(5) NOT NULL,
    [ndcproductcode] char(4) NOT NULL,
    [ndcpackagesize] char(2) NOT NULL,
    [drugname] char(30) NOT NULL,
    [druggenclass] char(15) NOT NULL,
    [drugform] char(15) NOT NULL,
    [therapeutclass] char(15) NOT NULL,
    [schedulecode] char(15) NOT NULL,
    [otcind] char(1) NOT NULL,
    [drugmaint] char(1) NOT NULL,
    [compoundind] int NOT NULL,
    [rxprovidtype] int NOT NULL,
    [rxprovid] char(15) NOT NULL,
    [ingrcost] money NOT NULL,
    [dispfee] money NOT NULL,
    [taxamt] money NOT NULL,
    [dayssupply] int NOT NULL,
    [macreduct] char(1) NOT NULL,
    [refillind] int NOT NULL,
    [drugtypecode] int NOT NULL,
    [refillauth] int NOT NULL,
    [diagcode] varchar(8) NOT NULL,
    [prodselectcode] int NOT NULL,
    [basisofcost] int NOT NULL,
    [priorauth] char(12) NOT NULL,
    [certificationnmbr] char(15) NOT NULL,
    [levelofservice] int NOT NULL,
    [prescorigincode] int NOT NULL,
    [customarycharge] money NOT NULL,
    [rxdatewritten] char(10) NOT NULL,
    [drugutilreview] char(2) NOT NULL,
    [formularyid] char(1) NOT NULL,
    [unitAWP] int NOT NULL,
    [unitMAC] int NOT NULL,
    [drugcatcode] char(1) NOT NULL,
    [drugdeacode] char(1) NOT NULL,
    [desidrugid] char(1) NOT NULL,
    [unitdoseid] int NOT NULL,
    [pharmacyid] char(12) NOT NULL,
    [pharmacyname] char(30) NOT NULL,
    [pharmacycity] char(20) NOT NULL,
    [pharmacystate] char(2) NOT NULL,
    [genericid] char(1) NOT NULL,
    [drugnamegeneric] char(30) NOT NULL,
    [drugnamebrand] char(30) NOT NULL,
    [drugclass] char(1) NOT NULL,
    [pharmacytaxid] char(9) NOT NULL,
    [createid] varchar(120) NOT NULL,
    [createdate] datetime NOT NULL,
    [updateid] varchar(120) NOT NULL,
    [lastupdate] datetime NOT NULL,
    [drugstrength] char(25) NOT NULL,
    [RxLastName] char(60) NOT NULL,
    [PharmacistId] char(15) NOT NULL,
    [PharmacistIdQual] char(2) NOT NULL,
    [RxNumberQual] char(1) NOT NULL,
    [SubmissionClarification] char(2) NOT NULL,
    [ProductQual] char(2) NOT NULL,
    [PriorAuthType] char(2) NOT NULL,
    [OtherCoverageCode] char(2) NOT NULL,
    [DelayReason] char(2) NOT NULL,
    [PlaceOfService] char(2) NOT NULL,
    [IcdVersion] char(1) NOT NULL,
    [OtherPayerId] char(15) NOT NULL,
    [OtherPayerIdQual] char(2) NOT NULL,
    [OtherPayerDate] char(10) NOT NULL,
    [OtherPayerRejects] char(3) NOT NULL,
    [OtherPayerId2] char(15) NOT NULL,
    [OtherPayerIdQual2] char(2) NOT NULL,
    [OtherPayerDate2] char(10) NOT NULL,
    [OtherPayerRejects2] char(3) NOT NULL,
    [ProfServiceFee] money NOT NULL,
    [IncentiveAmt] money NOT NULL,
    [OtherAmt] money NOT NULL,
    [PatientPaidAmt] money NOT NULL,
    [GrossAmtDue] money NOT NULL,
    [OtherPayerAmtPaid] money NOT NULL,
    [OtherPayerAmtPaid2] money NOT NULL,
    [OtherPayerPatientRespAmt] money NOT NULL,
    [OtherPayerPatientRespAmt2] money NOT NULL,
    [NetAmtDue] money NOT NULL,
    [UnitOfMeasure] char(2) NOT NULL
);
