CREATE TABLE [plandata_rx_production].[dbo].[referral]
(
    [referralid] ident DEFAULT (' ') NOT NULL,
    [enrollid] ident DEFAULT (' ') NOT NULL,
    [memid] ident DEFAULT (' ') NOT NULL,
    [servicecode] ident DEFAULT (' ') NOT NULL,
    [COB] zint DEFAULT (0) NOT NULL,
    [referto] ident DEFAULT (' ') NOT NULL,
    [effdate] smalldatetime DEFAULT ('01/01/1980') NOT NULL,
    [referfrom] ident DEFAULT (' ') NOT NULL,
    [emergency] zint DEFAULT (0) NOT NULL,
    [authorizationid] char(30) DEFAULT (' ') NOT NULL,
    [lastupdate] lastupdatetype DEFAULT (getdate()) NOT NULL,
    [referraldate] smalldatetime NULL,
    [transferinout] zint DEFAULT (0) NOT NULL,
    [admitphys] longname DEFAULT (' ') NOT NULL,
    [disdiagnosis] udtdiagcode DEFAULT (' ') NOT NULL,
    [admitdate] smalldatetime NULL,
    [numappt] zint DEFAULT (0) NOT NULL,
    [dischargedate] smalldatetime NULL,
    [tier1] zint DEFAULT (0) NOT NULL,
    [tier2] zint DEFAULT (0) NOT NULL,
    [staytype1] zint DEFAULT (0) NOT NULL,
    [termdate] smalldatetime DEFAULT ('12/31/2078') NOT NULL,
    [staytype2] zint DEFAULT (0) NOT NULL,
    [issueinitials] ident DEFAULT (' ') NOT NULL,
    [actual1] zint DEFAULT (0) NOT NULL,
    [actual2] zint DEFAULT (0) NOT NULL,
    [actualstay1] zint DEFAULT (0) NOT NULL,
    [actualstay2] zint DEFAULT (0) NOT NULL,
    [daysdenied] zint DEFAULT (0) NOT NULL,
    [deferreddliab] zint DEFAULT (0) NOT NULL,
    [reinsurance] zint DEFAULT (0) NOT NULL,
    [costest] zmoney DEFAULT (0) NOT NULL,
    [perdiemest] zmoney DEFAULT (0) NOT NULL,
    [accchg] zmoney DEFAULT (0) NOT NULL,
    [createdate] createdatetype DEFAULT (getdate()) NOT NULL,
    [createid] udtuserid DEFAULT (suser_sname()) NOT NULL,
    [updateid] udtuserid DEFAULT (suser_sname()) NOT NULL,
    [diagnosis] udtdiagcode DEFAULT (' ') NOT NULL,
    [admit] zint DEFAULT (0) NOT NULL,
    [status] umstatustype DEFAULT (' ') NOT NULL,
    [numremappt] zint DEFAULT (0) NOT NULL,
    [acuity] typecode DEFAULT (' ') NOT NULL,
    [attprovid] ident DEFAULT (' ') NOT NULL,
    [admtprovid] ident DEFAULT (' ') NOT NULL,
    [self] yesnotype DEFAULT ('N') NOT NULL,
    [asstsurgeon] ident DEFAULT (' ') NOT NULL,
    [authstatus] umstatustype DEFAULT (' ') NOT NULL,
    [hasassist] yesnotype DEFAULT ('N') NOT NULL,
    [receiptdate] smalldatetime NULL,
    [seendate] smalldatetime NULL,
    [userid] zint DEFAULT (0) NOT NULL,
    [outofarea] yesnotype DEFAULT ('N') NOT NULL,
    [ispredetermination] yesnotype DEFAULT ('N') NOT NULL,
    [paytoaffiliationid] ident DEFAULT (' ') NOT NULL,
    [hasdocuments] yesnotype DEFAULT ('N') NOT NULL,
    [isautodischargedate] yesnotype DEFAULT ('Y') NOT NULL,
    [referfromnetwork] ident DEFAULT (' ') NOT NULL,
    [pendclaims] yesnotype DEFAULT ('N') NOT NULL,
    [refertoprovtype] ident DEFAULT (' ') NOT NULL,
    [refertopar] yesnotype DEFAULT ('Y') NOT NULL,
    [refertolocation] char(2) DEFAULT (' ') NOT NULL,
    [isglobal] yesnotype DEFAULT ('N') NOT NULL,
    [accidentcause] char(1) DEFAULT (' ') NOT NULL,
    [accidentdate] datetime NULL,
    [investigation] yesnotype DEFAULT ('N') NOT NULL,
    [lmpdate] datetime NULL,
    [estdeldate] datetime NULL,
    [surgerydatetime] datetime NULL,
    [decrementtype] char(3) DEFAULT ('SVC') NOT NULL,
    [surgerysuggested] yesnotype DEFAULT ('N') NOT NULL,
    [appeal] char(1) DEFAULT ('N') NOT NULL,
    [appealdate] smalldatetime DEFAULT ('12/31/2078') NOT NULL,
    [reviewtype] char(1) DEFAULT ('A') NOT NULL,
    [beneprefid] ident DEFAULT (' ') NOT NULL,
    [appealoutcome] shortdesctype DEFAULT (' ') NOT NULL,
    [penaltyapplies] yesnotype DEFAULT ('N') NOT NULL,
    [retroreview] yesnotype DEFAULT ('N') NOT NULL,
    [reqlos] zint DEFAULT (0) NOT NULL,
    [actuallos] zint DEFAULT (0) NOT NULL,
    [processlogid] ident DEFAULT (' ') NOT NULL,
    [source] char(1) DEFAULT ('U') NOT NULL,
    [h278responseneeded] char(1) DEFAULT ('N') NOT NULL,
    [h278responsesent] datetime DEFAULT ('1/1/1900') NOT NULL,
    [h278processlogdetailid] ident DEFAULT (' ') NOT NULL,
    [h278responsestatus] char(1) DEFAULT ('N') NOT NULL,
    [reqpatinfo] yesnotype DEFAULT ('N') NOT NULL,
    [h278haschanges] yesnotype DEFAULT ('N') NOT NULL,
    [dispositionid] ident NULL,
    [priority] char(1) NULL,
    [highlight] char(1) NULL,
    [nextreviewdate] smalldatetime NULL,
    [DiagnosisIcdVersion] char(1) NULL,
    [DisDiagnosisIcdVersion] char(1) NULL,
    [MergeFromReferralId] ident NULL,
    [IsConsolidated] yesnotype NULL,
    [ServiceAffilId] ident NULL,
    [DefaultContractId] ident NULL,
    [TOTALBUDGET] zmoney DEFAULT ((0.00)) NOT NULL,
    [USEDBUDGET] zmoney DEFAULT ((0.00)) NOT NULL,
    [IsBundled] yesnotype DEFAULT ('N') NULL,
    [trackingnumber] varchar(50) NULL,
    [ReqTotalBudget] zmoney DEFAULT ((0)) NOT NULL,
    [ApplyDecrement] char(1) DEFAULT ('H') NOT NULL,
    CONSTRAINT [PKreferral] PRIMARY KEY ([referralid])
);
