/* Live SQL Server schema from INFORMATION_SCHEMA and key metadata. */
CREATE TABLE [plandata_rx_production].[dbo].[provider]
(
    [provid] char(15) NOT NULL, -- Primary key of the provider table | PK marker: X
    [entityid] char(15) NOT NULL, -- Primary key from the entity table | FK marker: X
    [specialtycode] char(15) NOT NULL, -- Primary key of the specialty table | FK marker: X
    [provtype] char(15) NOT NULL, -- Primary key of the providertype table | FK marker: X
    [fedid] char(12) NOT NULL, -- Federal Tax Identifier
    [fullname] varchar(95) NOT NULL, -- Fullname of the entry in provider
    [exthours] int NOT NULL, -- OBSOLETE- Now an affiliationattribute record
    [profdesig] char(15) NOT NULL, -- References proftitle(profdesig) - Provider's professional designation | FK marker: X
    [status] char(10) NOT NULL, -- Status of the entry in provider
    [ethnicid] char(15) NOT NULL, -- Primary key of the ethnicity table | FK marker: X
    [servlocation] int NOT NULL, -- Service Location
    [taxexempt] char(1) NOT NULL, -- Is provider organization a tax exempt entity. eg a non-profit hospital
    [medicarepar] char(1) NOT NULL, -- Is provider a medicare participant flag. If flag is set to true then reimbursment rate is slightly higher than non-participating medicare providers for medicare based claims.
    [upin] char(15) NOT NULL, -- Universal provider identifier
    [credentialstatus] char(15) NOT NULL, -- Credentialed/Uncredentialed status of the provider
    [gpciid] char(15) NOT NULL, -- Primary key of the gpci table | FK marker: X
    [provwatch] char(1) NOT NULL, -- OBSOLETE- Provider watch flag. When set to true claims will pend for review.
    [createid] varchar(120) NOT NULL, -- Id of the user who created this record
    [createdate] datetime NOT NULL, -- Date this record was created
    [lastupdate] datetime NOT NULL, -- Date this record was last updated
    [updateid] varchar(120) NOT NULL, -- Id of the user who last updated this record
    [xtrnid] char(30) NOT NULL, -- External provider id number
    [pin] char(30) NOT NULL, -- NOT USED
    [handicapaccess] char(1) NOT NULL, -- Used to track Handicap accessability for this provider.
    [sex] char(1) NOT NULL, -- Provider gender
    [dob] datetime NULL, -- Date of Birth
    [overrideroleid] char(15) NOT NULL, -- User security role used to override the "Pend for Manual Review" flag
    [lienmailtomember] char(1) NOT NULL, -- 2.6 (045): Indicates if lien checks are sent to the member instead of the provider
    [rentalnetwork] char(1) NOT NULL, -- 2.6 (057): Indicates if the provider/network is part of a rental network
    [autocreated] char(1) NOT NULL, -- 2.6 (077): Indicates if provider was auto generated by the system.
    [autoupdated] char(1) NOT NULL, -- 2.6 (077): Indicates if provider was auto updated by the system. (I.E. plan affiliation is terminated) System updates using default information for the program and sets to Y.
    [npi] char(10) NULL, -- National Provider Identifier
    [externalediting] char(1) NOT NULL, -- Yes - means claims for this member/provider WILL BE SENT to Ingenix iCES claims editing module. No - means claims for this member/provider WILL NOT BE SENT to Ingenix iCES claims editing module.FYI: If the value of "externalediting" is Yes in the table,
    [FedIdType] char(15) NULL, -- Value representing fedidtype
    [PoaExempt] char(1) NOT NULL, -- Value representing poaexempt
    [FiscalYearEndMonth] int NOT NULL, -- Value representing fiscalyearendmonth
    [FiscalYearEndDay] int NOT NULL, -- Value representing fiscalyearendday
    [Ssn] char(15) NULL, -- Provider's Social Security Number
    [ExternalId] varchar(15) NULL, -- Identifier for external
    [NPIType] char(1) NOT NULL, -- Value representing npitype
    [Parking] char(1) NOT NULL,
    [WheelChairRamp] char(1) NOT NULL,
    [Elevator] char(1) NOT NULL,
    [BathroomAccomodation] char(1) NOT NULL,
    [ExamRoom] char(1) NOT NULL,
    [ExamTable] char(1) NOT NULL
);
