CREATE TABLE [plandata_rx_production].[dbo].[authservice]
(
    [referralid] ident DEFAULT (' ') NOT NULL,
    [sequence] zint DEFAULT (0) NOT NULL,
    [codeid] char(11) DEFAULT (' ') NOT NULL,
    [medcoverage] char(1) DEFAULT (' ') NOT NULL,
    [carelevel] char(1) DEFAULT (' ') NOT NULL,
    [servcategory] cattype DEFAULT ('CPT') NOT NULL,
    [status] statustype DEFAULT ('OPEN') NOT NULL,
    [xreasoncode] typecode DEFAULT (' ') NOT NULL,
    [overridecontract] yesnotype DEFAULT ('N') NOT NULL,
    [totalunits] zmoney DEFAULT ((0)) NOT NULL,
    [usedunits] zmoney DEFAULT ((0)) NOT NULL,
    [actualunits] zmoney DEFAULT ((0)) NOT NULL,
    [tier] ident DEFAULT (' ') NOT NULL,
    [dosdate] smalldatetime NOT NULL,
    [globalday] zint DEFAULT (0) NOT NULL,
    [reqcodeid] char(11) DEFAULT (' ') NOT NULL,
    [catid] ident DEFAULT (' ') NOT NULL,
    [subcatid] ident DEFAULT (' ') NOT NULL,
    [svcgroupid] ident DEFAULT (' ') NOT NULL,
    [reqcatid] ident DEFAULT (' ') NOT NULL,
    [reqsubcatid] ident DEFAULT (' ') NOT NULL,
    [reqsvcgrpid] ident DEFAULT (' ') NOT NULL,
    [createid] udtuserid DEFAULT (suser_sname()) NOT NULL,
    [createdate] createdatetype DEFAULT (getdate()) NOT NULL,
    [updateid] udtuserid DEFAULT (suser_sname()) NOT NULL,
    [lastupdate] lastupdatetype DEFAULT (getdate()) NOT NULL,
    [modcode] modifiertype DEFAULT (' ') NOT NULL,
    [modcode2] modifiertype DEFAULT (' ') NOT NULL,
    [toothnumber] toothtype DEFAULT (' ') NOT NULL,
    [toothsurface] char(5) DEFAULT (' ') NOT NULL,
    [approvedcodeid] servicecode DEFAULT (' ') NOT NULL,
    [modcode3] modifiertype DEFAULT (' ') NOT NULL,
    [modcode4] modifiertype DEFAULT (' ') NOT NULL,
    [modcode5] modifiertype DEFAULT (' ') NOT NULL,
    [globaltemplate] yesnotype DEFAULT ('N') NOT NULL,
    [negotiatedcontract] ident DEFAULT (' ') NOT NULL,
    [negotiatedterm] ident DEFAULT (' ') NOT NULL,
    [negotiatedvalue] zmoney DEFAULT (0) NOT NULL,
    [ispatientresp] yesnotype DEFAULT ('N') NOT NULL,
    [ndcprodname] char(50) DEFAULT (' ') NOT NULL,
    [appndcgroupname] char(50) DEFAULT (' ') NOT NULL,
    [interqualid] ident DEFAULT (' ') NOT NULL,
    [meddirectorid] ident DEFAULT (' ') NOT NULL,
    [requestedunits] zmoney DEFAULT ((0)) NOT NULL,
    [svcprocamount] zmoney DEFAULT (0.0000) NOT NULL,
    [initialreferralid] ident NULL,
    [initialreferralseq] zint NULL,
    [detailsourcetype] char(1) DEFAULT (' ') NOT NULL,
    [initialreferraltemplate] yesnotype DEFAULT ('N') NULL,
    [dentalareaid] ident DEFAULT (' ') NOT NULL,
    [downcodesurfacecount] zint NULL,
    [DeterminationDate] udtshortdate NULL,
    [H278RecordSequence] zint NULL,
    [location] char(2) DEFAULT ('') NOT NULL,
    [Frequency] char(8) DEFAULT ('') NOT NULL,
    [EffDate] smalldatetime DEFAULT ('01/01/1980') NOT NULL,
    [TermDate] smalldatetime DEFAULT ('12/31/2078') NOT NULL,
    [ReqEffDate] smalldatetime NULL,
    [ReqTermDate] smalldatetime NULL,
    [decrementtype] char(3) NULL,
    [TotalBudget] zmoney DEFAULT ((0)) NOT NULL,
    [UsedBudget] zmoney DEFAULT ((0)) NOT NULL,
    [ReqTotalBudget] zmoney DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PKauthservice] PRIMARY KEY ([referralid], [sequence], [globaltemplate])
);
